// Link to a PDF generated by scripts/pdf/build-pdf.tsx into /public/pdf.
export function DownloadLink({ href, label, className = "" }: { href: string; label: string; className?: string }) {
  return (
    <a href={href} download type="application/pdf" className={`btn btn-line no-print ${className}`}>
      <svg aria-hidden="true" viewBox="0 0 24 24" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
        <path d="M12 4v11M7.5 10.5L12 15l4.5-4.5M5 19.5h14" />
      </svg>
      {label}
    </a>
  );
}
