import manifest from "@/lib/images.generated.json";

type Entry = { dir: string; width: number; height: number; widths: number[]; blur: string };
const images = manifest as Record<string, Entry>;

// Responsive photo: AVIF + WebP srcsets generated by scripts/images/build.mjs, blur placeholder,
// explicit ratio (no layout shift), focal point kept when cropped.
export function Photo({
  id,
  alt,
  sizes,
  ratio,
  focal = [0.5, 0.5],
  priority = false,
  className = "",
  imgClassName = "",
}: {
  id: string;
  alt: string;
  sizes: string;
  /** width / height of the frame, e.g. 4 / 5. Defaults to the photo's own ratio. */
  ratio?: number;
  focal?: [number, number];
  priority?: boolean;
  className?: string;
  imgClassName?: string;
}) {
  const img = images[id];
  if (!img) throw new Error(`Unknown photo "${id}": run npm run images`);
  const srcset = (ext: string) => img.widths.map((w) => `/img/${img.dir}/${w}.${ext} ${w}w`).join(", ");
  const fallback = img.widths.find((w) => w >= 960) ?? img.widths[img.widths.length - 1];
  const frameRatio = ratio ?? img.width / img.height;
  return (
    <div
      className={`relative overflow-hidden bg-navy ${className}`}
      style={{
        aspectRatio: String(frameRatio),
        backgroundImage: `url(${img.blur})`,
        backgroundSize: "cover",
        backgroundPosition: `${focal[0] * 100}% ${focal[1] * 100}%`,
      }}
    >
      <picture>
        <source type="image/avif" srcSet={srcset("avif")} sizes={sizes} />
        <source type="image/webp" srcSet={srcset("webp")} sizes={sizes} />
        <img
          src={`/img/${img.dir}/${fallback}.webp`}
          alt={alt}
          width={img.width}
          height={img.height}
          loading={priority ? "eager" : "lazy"}
          fetchPriority={priority ? "high" : "auto"}
          decoding={priority ? "sync" : "async"}
          className={`absolute inset-0 h-full w-full object-cover ${imgClassName}`}
          style={{ objectPosition: `${focal[0] * 100}% ${focal[1] * 100}%` }}
        />
      </picture>
    </div>
  );
}
